config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, only: [:index, :new, :create, :edit, :update]
  end

  namespace :client do 
    resources :memberships, only: [:index]
  end

  get 'pages/index'
  root to: "pages#index"

  # inicio y cierre de sesión
  get '/users/sign_in', to: 'sessions#new'
  post '/users/sign_in', to: 'sessions#create'
  delete '/users/sign_out', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # agrega validaciones al password(tamaño, confirmación,presente)
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end 

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "Se ha creado con éxito"
    else
      render :new
    end
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def update 
    @user = User.find(params[:id])
  end

  # metodo para permitir que atributos pueden ser accedidos
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AuthenticateHelper
end

app/controllers/client/memberships_controller.rb
class Client::MembershipsController < ApplicationController
  def index
    @memberships = nil
  end
end

app/controllers/dashboard_controller.rb
class DashboardController > ApplicationController
  include AuthenticateHelper

  before_action :authenticate_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include AuthenticateHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_dashboard_user, only: [:new]

  def new
    @user = User.new
  end

  def create
    # 1- Verifica si existe el email
    @user = User.find_by(email: params['email'])
    if @user
      # 2- Verifica la contraseña
      if @user.authenticate(params['password'])
        session[:current_user] = @user.id
        redirect_to client_memberships_path, notice: "Te haz logeado exitosamente"
      else 
        flash[:alert] = "Password incorrecto"
        render :new, status: :unprocessable_entity
      end
    else 
      render :new, status: :unprocessable_entity, alert: "No existe el email"
    end
  end

  def destroy 
    reset_session
    redirect_to  root_path
  end
  
  private 

  def redirect_dashboard_user
    redirect_to client_memberships_path if user_signed_in? 
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authenticate_helper.rb
module AuthenticateHelper

  # Retorna información del usuario actual
  def current_user
    if session[:current_user]
      current_user ||= User.find_by(id: session[:current_user])
    end
  end

  # Retorna boolean si el usuario esta logeado o no
  def user_signed_in? 
    result = false
    if session[:current_user]
      result = true
    end
    
    result
  end

  # Retorna al login o home, dependiendo del estado de session
  def authenticate_user
    if session[:current_user]
      @user = User.find_by(id: session[:current_user])
      if @user
        
      end
    else
      redirect_to users_sign_in_path
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/users/_form.html.erb
<%= form_with model: user, url: admin_users_path(user) do |form| %>

  <% if user.errors.any? %>
    <% user.errors.full_messages.each do |error| %>
      <p> <%= error %> </p>
    <% end %>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>
  
  <div class="mb-3">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/admin/users/edit.html.erb
<h1>ACTUALIZAR FORMULARIO</h1>

<%= render partial: "admin/users/edit", locals: {user: @user} %>

app/views/admin/users/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1> Formulario </h1>

<%= render partial: "admin/users/form", locals:{user: @user} %>

app/views/client/memberships/index.html.erb
PORTAL DE USUARIO

<%= link_to "Salir de cuenta", users_sign_out_path, method: :delete, data: {confirm: "estás seguro ? "} %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-white fw-bold" href="#">Gym Municipal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="#">Quienes Somos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="#">Contactanos</a>
        </li>
        <li class="nav-item">
          <% unless user_signed_in?  %>
            <%= link_to users_sign_in_path, style:"color:white" do %>
              <i class="bi bi-person" style="font-size:30px;"></i>
            <% end %>
          <% else%>
            <%= link_to users_sign_out_path, method: :delete, style:"color:white" do %>
              <i class="bi bi-box-arrow-left" style="font-size:30px;"></i>
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <% if flash[:alert]%>
      <div> <%= flash[:alert] %> </div>
    <% end %>
    <% if flash[:notice] %>
      <div> <%= flash[:notice] %> </div>
    <% end %>
    <%= yield %>
    <% console %>
  </body>
</html>

app/views/pages/index.html.erb
<section class="splide" aria-label="Splide Basic HTML Example">
  <div class="splide__track">
		<ul class="splide__list">
			<li class="splide__slide"> <%= image_tag('gym1.jpg', class:'splide_container') %> </li>
		</ul>
  </div>
</section>

<script>
  document.addEventListener( 'DOMContentLoaded', function() {
    var splide = new Splide( '.splide', {
			height: '30rem',
			cover: true,
		});
    splide.mount();
  } );
</script>


<!-- Clases y Horarios -->
<section id="clases" class="py-5">
    <div class="container">
        <h2 class="text-center mb-5">Clases Disponibles</h2>
        <div class="row">
            <div class="col-lg-4">
                <div class="card h-100">
                    <img src="https://via.placeholder.com/350x200" class="card-img-top" alt="Cardio">
                    <div class="card-body">
                        <h5 class="card-title">Cardio</h5>
                        <p class="card-text">Mejora tu resistencia y quema calorías con nuestras intensas clases de cardio.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card h-100">
                    <img src="https://via.placeholder.com/350x200" class="card-img-top" alt="Yoga">
                    <div class="card-body">
                        <h5 class="card-title">Yoga</h5>
                        <p class="card-text">Encuentra el equilibrio entre cuerpo y mente con nuestras clases de yoga.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card h-100">
                    <img src="https://via.placeholder.com/350x200" class="card-img-top" alt="Pesas">
                    <div class="card-body">
                        <h5 class="card-title">Entrenamiento de Pesas</h5>
                        <p class="card-text">Fortalece tus músculos con nuestras sesiones de levantamiento de pesas.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="entrenadores" class="py-5 bg-light">
    <div class="container">
        <h2 class="text-center mb-5">Nuestros Entrenadores</h2>
        <div class="row text-center">
            <div class="col-lg-4">
                <div class="feature-icon text-primary mb-3">
                    <i class="bi bi-person-fill"></i>
                </div>
                <h5>Juan Pérez</h5>
                <p>Especialista en entrenamiento funcional.</p>
            </div>
            <div class="col-lg-4">
                <div class="feature-icon text-primary mb-3">
                    <i class="bi bi-person-fill"></i>
                </div>
                <h5>María González</h5>
                <p>Entrenadora de yoga y bienestar.</p>
            </div>
            <div class="col-lg-4">
                <div class="feature-icon text-primary mb-3">
                    <i class="bi bi-person-fill"></i>
                </div>
                <h5>Carlos López</h5>
                <p>Especialista en levantamiento de pesas y crossfit.</p>
            </div>
        </div>
    </div>
</section>

<section id="membresias" class="py-5">
    <div class="container">
        <h2 class="text-center mb-5">Nuestras Membresías</h2>
        <div class="row text-center">
            <div class="col-lg-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">Básico</h5>
                        <p class="card-text">Acceso a las áreas comunes del gimnasio y clases grupales.</p>
                        <h3>$30/mes</h3>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">Premium</h5>
                        <p class="card-text">Acceso completo al gimnasio y todas las clases, además de 9 sesiones mensuales con un entrenador personal.</p>
                        <h3>$50/mes</h3>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">VIP</h5>
                        <p class="card-text">Acceso completo, entrenador personal y nutricionista incluido.</p>
                        <h3>$80/mes</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="testimonials">
    <div class="container">
        <h2 class="text-center mb-5">Lo que dicen nuestros clientes</h2>
        <div class="row">
            <div class="col-lg-6">
                <blockquote class="blockquote">
                    <p>"FitLife cambió mi vida. Ahora me siento más saludable y con más energía."</p>
                    <footer class="blockquote-footer">Ana Martínez</footer>
                </blockquote>
            </div>
            <div class="col-lg-6">
                <blockquote class="blockquote">
                    <p>"Un gimnasio con instalaciones increíbles y entrenadores muy profesionales."</p>
                    <footer class="blockquote-footer">Pedro García</footer>
                </blockquote>
            </div>
        </div>
    </div>
</section>